# Generated by Django 3.1.1 on 2020-09-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='nome',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
