# Generated by Django 3.1.1 on 2020-09-18 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medico',
            name='telefone',
            field=models.IntegerField(default=''),
            preserve_default=False,
        ),
    ]
